name: Build libsm64

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install SDL2 and GLEW
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libglew-dev

      #- name: Print Folder Structure
      #  if: runner.os == 'Linux'
      #  run: ls -l

      - name: Linux - Build Base Binary
        if: runner.os == 'Linux'
        run: |
          make lib
          make test

      #- name: Print Folder Structure
      #  if: runner.os == 'Linux'
      #  run: |
      #    ls -l
      #    ls -l ./build
      #    ls -l ./dist

      - name: Linux - Upload Build
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: libsm64
          path: |
            ./dist
            ./build

  #Release:
  #  name: "Snapshot Release"
  #  runs-on: "ubuntu-latest"
  #  needs: Build

  #  steps:
  #    - name: Download artifacts
  #      uses: actions/download-artifact@v3

  #    - name: Create a Release
  #      uses: "marvinpinto/action-automatic-releases@latest"
  #      with:
  #        repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #        automatic_release_tag: "latest"
  #        prerelease: true
  #        title: "Snapshot Build"
  #        files: |
  #          /home/runner/work/sort_cuda/sort_cuda/sort_std
  #          /home/runner/work/sort_cuda/sort_cuda/sort_cuda
